// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Direct_Barber.Models;

public partial class Solicitud
{
    public int IdSolicitud { get; set; }

    public int? IdEstado { get; set; }

    public int? IdCliente { get; set; }

    public int? IdBarbero { get; set; }

    public decimal? PrecioServicio { get; set; }

    public int? TipoServicio { get; set; }

    public string Dirección { get; set; }

    public DateTime? Fecha { get; set; }

    public string Descripcion { get; set; }

    public virtual Usuario IdBarberoNavigation { get; set; }

    public virtual Usuario IdClienteNavigation { get; set; }

    public virtual EstadoSolicitud IdEstadoNavigation { get; set; }

    public virtual TipoSer TipoServicioNavigation { get; set; }
}