// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Direct_Barber.Models;

public partial class TipoSer
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Foto { get; set; }
    [NotMapped]
    public IFormFile ImagenFile { get; set; }


    public decimal Precio { get; set; }

    public virtual ICollection<Solicitud> Solicituds { get; set; } = new List<Solicitud>();
}